kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
  namespace: nfs
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 100m
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: dranixj.me/nfs
            - name: NFS_SERVER
              #value: 10.1.0.79
              value: 172.12.3.100
            - name: NFS_PATH
              #value: /nfsshare
              value: /mnt/sharefolder
      volumes:
        - name: nfs-client-root
          nfs:
            #server: 10.1.0.79
            #path: /nfsshare
            server: 172.12.3.100
            path: /mnt/sharefolder