apiVersion: v1
kind: ServiceAccount
metadata:
  name: dranixj
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterrole-bind-admin
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: dranixj
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io