apiVersion: v1
kind: Pod
metadata:
  name: busybox-curl
  namespace: default
spec:
  containers:
  - name: busybox-curl
    image: odise/busybox-curl:latest
    resources:
      limits:
        cpu: 100m
        memory: 100m
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent