apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: kube-ops
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs-storageclass
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi