apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
  namespace: kube-ops
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs-storageclass
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi